basePath: /
host: localhost:8080
info:
  contact:
    email: soberkoder@gmail.com
    name: API Support
  description: This is a sample service for managing orders
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Orders API
  version: "1.0"
paths: {}
swagger: "2.0"
